version: '3.0'

services:
  app:
    image: activepieces/ap-base:3
    container_name: app
    environment:
      AP_JWT_SECRET: super-secret
      AP_POSTGRES_HOST: postgres
      AP_SIGN_UP_ENABLED: 'false'
      AP_REDIS_HOST: redis
      AP_EXECUTION_MODE: UNSANDBOXED
    user: 1000:1000
    ports:
     - "3000:3000"
     - "4200:4200"
     - "9229:9229"
     - "9222:9222"
    networks:
      - activepieces_dev
    volumes:
     - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh -c "npm i && (npx nx serve backend & npx nx serve ui-core)"
    depends_on:
     - postgres
     - redis

  postgres:
    image: postgres:14.4
    container_name: postgres
    environment:
      POSTGRES_DB: activepieces
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A79Vm5D4p2VQHOp2gd5
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - activepieces_dev
    #command: -c log_statement=all -c shared_preload_libraries=auto_explain -c auto_explain.log_min_duration=0

  redis:
    image: redis:7.0.7
    container_name: redis
    volumes:
      - redis_data_dev:/data
    networks:
      - activepieces_dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  activepieces_dev:
