## **************** DOCUMENTATION ****************
##
## Please refer to the documentation for more information on how to use this file. 
## https://www.activepieces.com/docs/contributing/development-setup/docker-compose
##
## ***********************************************
version: '3.0'

services:

  app:
    image: activepieces/ap-base:3
    platform: linux/arm64
    container_name: activepieces
    environment:
      AP_JWT_SECRET: super-secret
      AP_POSTGRES_HOST: postgres
      AP_SIGN_UP_ENABLED: 'false'
      AP_REDIS_HOST: redis
      AP_EXECUTION_MODE: SANDBOXED
      AP_ENVIRONMENT: prod
    privileged: true
    ports:
     - "3000:3000"
     - "4200:4200"
     - "9229:9229"
     - "9222:9222"
    networks:
      - activepieces_dev
    profiles:
      - full
    volumes:
     - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh -c "npm i && (npx nx serve backend & npx nx serve ui-core)"
    depends_on:
     - postgres
     - redis

  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_DB: activepieces
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A79Vm5D4p2VQHOp2gd5
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - activepieces_dev
    #command: -c log_statement=all -c shared_preload_libraries=auto_explain -c auto_explain.log_min_duration=0

  redis:
    image: redis:7.0.7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - activepieces_dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  activepieces_dev:
