## **************** DOCUMENTATION ****************
##
## Please refer to the documentation for more information on how to use this file.
## https://www.activepieces.com/docs/contributing/development-setup/docker-compose
##
## ***********************************************
version: '3.0'

services:
  app:
    image: activepieces/ap-base:7
    container_name: ap
    environment:
      AP_CACHE_PATH: /usr/cache
      AP_DB_TYPE: POSTGRES
      AP_ENCRYPTION_KEY: 7e19fad4c13eaea8f657afb12e8f9c40
      AP_EXECUTION_MODE: UNSANDBOXED
      AP_JWT_SECRET: super-secret
      AP_POSTGRES_DATABASE: activepieces
      AP_POSTGRES_HOST: postgres
      AP_POSTGRES_PASSWORD: postgres
      AP_POSTGRES_PORT: 5432
      AP_POSTGRES_USERNAME: postgres
      AP_QUEUE_MODE: REDIS
      AP_REDIS_HOST: redis
      AP_REDIS_PORT: 6379
      AP_SIGN_UP_ENABLED: false
    user: 1000:1000
    ports:
     - "3000:3000"
     - "4200:4200"
     - "9229:9229"
    networks:
      - activepieces_dev
    volumes:
     - ./:/usr/src/app
    working_dir: /usr/src/app
    entrypoint:
      - npm
      - start
    depends_on:
     - postgres
     - redis

  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    container_name: pg
    environment:
      POSTGRES_DB: activepieces
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - activepieces_dev
    #command: -c log_statement=all -c shared_preload_libraries=auto_explain -c auto_explain.log_min_duration=0

  redis:
    image: redis:7.0.7
    container_name: rd
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - activepieces_dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  activepieces_dev:
