import {
    ActionContext,
    PieceAuthProperty,
    Property,
    Validators,
    createAction,
} from '@activepieces/pieces-framework';
import { EPNAuth } from '../../index';
import { EPNCommon } from '../common';
import { createApi } from '../api';

const cards = [
    {
        bin: 486555,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'Visa',
        adv_operators: [],
        pr_id: 2,
        id: 9,
    },
    {
        bin: 537100,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
        ],
        pr_id: 2,
        id: 10,
    },
    {
        bin: 404038,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'Visa',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 4,
                name: 'TikTok',
                rating: 1,
                icon: {
                    id: 20,
                    type: 'image/svg+xml',
                    title: 'tiktok.svg',
                    url: 'https://api.epn.net/storage/2023/02/14/8d932034fd7ba38acab81fb3674c4464fac7775a.svg',
                },
            },
        ],
        pr_id: 2,
        id: 11,
    },
    {
        bin: 428803,
        is_credit: 1,
        is_3ds: 1,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'Visa',
        adv_operators: [],
        pr_id: 2,
        id: 12,
    },
    {
        bin: 512631,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
        ],
        pr_id: 2,
        id: 13,
    },
    {
        bin: 512998,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
        ],
        pr_id: 2,
        id: 16,
    },
    {
        bin: 513989,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
            {
                id: 4,
                name: 'TikTok',
                rating: 2,
                icon: {
                    id: 20,
                    type: 'image/svg+xml',
                    title: 'tiktok.svg',
                    url: 'https://api.epn.net/storage/2023/02/14/8d932034fd7ba38acab81fb3674c4464fac7775a.svg',
                },
            },
        ],
        pr_id: 2,
        id: 17,
    },
    {
        bin: 517746,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
        ],
        pr_id: 2,
        id: 18,
    },
    {
        bin: 519075,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
            {
                id: 4,
                name: 'TikTok',
                rating: 2,
                icon: {
                    id: 20,
                    type: 'image/svg+xml',
                    title: 'tiktok.svg',
                    url: 'https://api.epn.net/storage/2023/02/14/8d932034fd7ba38acab81fb3674c4464fac7775a.svg',
                },
            },
        ],
        pr_id: 2,
        id: 19,
    },
    {
        bin: 531993,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
        ],
        pr_id: 2,
        id: 20,
    },
    {
        bin: 534786,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
        ],
        pr_id: 2,
        id: 21,
    },
    {
        bin: 556150,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
            {
                id: 4,
                name: 'TikTok',
                rating: 2,
                icon: {
                    id: 20,
                    type: 'image/svg+xml',
                    title: 'tiktok.svg',
                    url: 'https://api.epn.net/storage/2023/02/14/8d932034fd7ba38acab81fb3674c4464fac7775a.svg',
                },
            },
        ],
        pr_id: 2,
        id: 22,
    },
    {
        bin: 556371,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
        ],
        pr_id: 2,
        id: 23,
    },
    {
        bin: 559292,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
        ],
        pr_id: 2,
        id: 24,
    },
    {
        bin: 540588,
        is_credit: 1,
        is_3ds: 1,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [],
        pr_id: 2,
        id: 25,
    },
    {
        bin: 428820,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'Visa',
        adv_operators: [],
        pr_id: 2,
        id: 29,
    },
    {
        bin: 428852,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'Visa',
        adv_operators: [],
        pr_id: 2,
        id: 30,
    },
    {
        bin: 52489763,
        is_credit: 1,
        is_3ds: 1,
        tariff: 'Advertisement cards',
        tariff_data: {
            id: 2,
            name: 'Advertisement cards',
            slug: 'adv',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '10.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [],
        pr_id: 2,
        id: 32,
    },
].concat([
    {
        bin: 4865551,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Universal cards',
        tariff_data: {
            id: 1,
            name: 'Universal cards',
            slug: 'all',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '15.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'Visa',
        adv_operators: [],
        pr_id: 2,
        id: 6,
    },
    {
        bin: 5371001,
        is_credit: 1,
        is_3ds: 0,
        tariff: 'Universal cards',
        tariff_data: {
            id: 1,
            name: 'Universal cards',
            slug: 'all',
            card_count_min: 1,
            card_count_max: 1,
            card_price: '15.00',
            replace_price: '0.00',
            start_balance: '1.00',
            duration: 720,
            type: 1,
            fee_topup: '0.0000',
        },
        type: 'MasterCard',
        adv_operators: [
            {
                id: 1,
                name: 'Facebook',
                rating: 0,
                icon: {
                    id: 13,
                    type: 'image/svg+xml',
                    title: 'facebook.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/0b872916e0d883f8fa070e8cf0f089fe9f6261be.svg',
                },
            },
            {
                id: 3,
                name: 'Google',
                rating: 1,
                icon: {
                    id: 14,
                    type: 'image/svg+xml',
                    title: 'google.svg',
                    url: 'https://api.epn.net/storage/2023/02/13/ca13f4fcb821ed52ce011a02ec75d09f687ffefb.svg',
                },
            },
            {
                id: 5,
                name: 'Taboola',
                rating: 2,
                icon: {
                    id: 21,
                    type: 'image/svg+xml',
                    title: 'taboola.svg',
                    url: 'https://api.epn.net/storage/2023/02/14/6802ea34c7de409fe71f3ff600ee945d56edc90e.svg',
                },
            },
            {
                id: 7,
                name: 'Outbrain',
                rating: 3,
                icon: {
                    id: 45,
                    type: 'image/svg+xml',
                    title: 'outbrain.svg',
                    url: 'https://api.epn.net/storage/2023/02/14/008a59a8a8910e0809d103f12a8aeac693b96b72.svg',
                },
            },
            {
                id: 35,
                name: 'PropellerAds',
                rating: 4,
                icon: {
                    id: 181,
                    type: 'image/png',
                    title: 'PAds_Logo_BB_Pantone.png',
                    url: 'https://api.epn.net/storage/2023/04/07/a3d3eea3d6d76a1030bbdefdcbe5723eb61accd7.png',
                },
            },
            {
                id: 32,
                name: 'clickadu',
                rating: 5,
                icon: {
                    id: 73,
                    type: 'image/png',
                    title: 'clickadu.png',
                    url: 'https://api.epn.net/storage/2023/03/10/ff43d78f0245ebdd2147f0f94c3fe70c372efc76.png',
                },
            },
        ],
        pr_id: 2,
        id: 7,
    },
]);

export const IssueCard = createAction({
    auth: EPNAuth,
    requireAuth: true,
    name: 'issue_card',
    displayName: 'Buy a card',
    description: 'Buy a card',
    props: {
        bin: Property.StaticDropdown({
            displayName: 'Card Type',
            description: 'Select card',
            required: true,
            options: {
                options: cards.map((card) => ({
                    value: card.bin,
                    label: `[${card.tariff_data.slug}] ${card.type} ${card.bin}`,
                })),
            },
        }),
    },
    async run(context) {
        throw new Error('Not implemented');
    },
});
