name: Build Cloud Image

on:
  workflow_dispatch:


jobs:
  Release:
    env:
      MY_VERSION: 17
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set RELEASE env var from package.json
        run: echo RELEASE=$(node --print "require('./package.json').version") >> $GITHUB_ENV

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to DigitalOcean Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          project: du7O4b0e8P
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          context: .
          file: ./Dockerfile
          build-args: |
            ENVIRONMENT=cloud
          platforms: |
            linux/amd64
          push: true
          tags: |
            registry.digitalocean.com/activepieces/activepieces:${{ env.RELEASE }}.${{ env.MY_VERSION }}
