name: Release Pieces

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  Release-Pieces:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup ~/.npmrc
        run: |
          cp .npmrc $HOME/.npmrc

      - name: Show ~/.npmrc
        run: |
          cat $HOME/.npmrc

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: build packages
        run: npx nx run-many --target=build --projects=tag:${{ vars.VENDOR_NAME}}

      - name: publish pieces packages
        run: npx ts-node tools/scripts/publish-pieces-to-npm.ts
        env:
          VENDOR_NAME: ${{ vars.VENDOR_NAME }}