name: Release Pieces

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/pieces/**'

jobs:
  Release-Pieces:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: build packages
        run: npx nx run-many --target=build --projects=tag:${{ secrets.VENDOR_NAME}}

      - name: copy project .npmrc to user level
        run: cp .npmrc $HOME/.npmrc

      - name: publish pieces packages
        run: npx ts-node tools/scripts/publish-pieces-to-npm.ts
        env:
          VENDOR_NAME: ${{ secrets.VENDOR_NAME }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: update pieces metadata
      #   run: npx ts-node -r tsconfig-paths/register -P packages/engine/tsconfig.lib.json tools/scripts/update-pieces-metadata/main.ts packages/pieces/framework
      #   env:
      #     AP_VENDOR_NAME: ${{ secrets.AP_VENDOR_NAME }}
      #     AP_CLOUD_API_KEY: ${{ secrets.AP_CLOUD_API_KEY }}
      #     AP_CLOUD_API_BASE: ${{ secrets.AP_CLOUD_API_BASE }}
